//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public string IBAN { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public int currency { get; set; }
        public int depositType { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual UsersJuridical UsersJuridical { get; set; }
        public virtual DepositType DepositType1 { get; set; }
        public virtual UsersLegal UsersLegal { get; set; }
    }
}
