//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPay
    {
        public int ID { get; set; }
        public int loanID { get; set; }
        public string payIBAN { get; set; }
        public decimal pAmount { get; set; }
        public System.DateTime payDate { get; set; }
    
        public virtual CurrentAccount CurrentAccount { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
