//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Transaction
    {
        public int ID { get; set; }
        public string srcIBAN { get; set; }
        public string destIBAN { get; set; }
        public decimal amount { get; set; }
        public int currency { get; set; }
        public System.DateTime tranDate { get; set; }
        public string StrTranDate { get; set; } //modificat
        public string tDescription { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual CurrentAccount CurrentAccount { get; set; }
        public virtual CurrentAccount CurrentAccount1 { get; set; }

        //MODIFICARI
        public string NumeSursa { get; set; }
        public string NumeDestinatie { get; set; }
        public string Semn { get; set; }
        public string TextCurrency { get; set; }
        public int IDFereastra { get; set; }
    }
}
